credentials: ../credentials.txt
jar: ../webin-cli-8.2.0.jar
excel_biosamples: BiosampleList.xlsx
excel_runs: ExperimentList.xlsx
excel_analysis: AnalysisList.xlsx

# If not set to True, the scripts will only generate the 
# files for submission (convert excel, generate xml, gz, etc)
# Recommended: True
submit: True

# Leave empty for it to be set at runtime in the terminal with the
# "--live" flag, or set to True or False here (mind the case)
# Recommended: True (the objects aren't made public until the study is public)
live: False

# Paths to where you want to store the files for submission.
# If empty it will be set to the current working directory by default
# Recommended: empty (defaults to current working directory)
sub_dir_runs:                             # analysis submission files
sub_dir_analysis:                         # runs submission files

assembly_level: scaffold                  # scaffold | contig | chromosome
mingaplength: 50                          # used only if scaffold & no AGP

